spring.application.name=demologin


spring.datasource.url=jdbc:mysql://localhost:3310/login

spring.datasource.username=yvam
spring.datasource.password=yvan123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#desactivar creaciona automatica de tablas con hibernate
spring.jpa.hibernate.ddl-auto=none


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration